env: "local"
instrument: "BTC_USDT"
mode: "grpc" #grpc, http, event

net:
  addr: ":3000"

snapshot:
  path: "/Users/andysu/Desktop/open-source/go-match/runtime/snapshot.bin"
  period: 60

consumer:
  stream: "SPOT_ORDERS"