env: "local"
instruments:
  - "BTC_USDT"
  - "ETH_USDT"

net:
  addr: ":3000"

snapshot:
  dir: "/Users/andysu/Desktop/open-source/go-match/runtime"
  period: 60

wal:
  dir: "/Users/andysu/Desktop/open-source/go-match/runtime"

consumer:
  stream: "SPOT_ORDERS"