server_name: nats3
port: 4222
http_port: 8222

jetstream {
  store_dir: /data
  max_mem: 1G
  max_file: 10G
}

cluster {
  name: nats-cluster
  port: 6222
  connect_retries: 30
  no_advertise: true
  routes: [
    nats://nats1:6222,
    nats://nats2:6222
  ]
}